language: node_js
node_js:
- "8"
- "9"

stages:
  - quality
  - compile
  - test
  - name: deploy
    if: branch = master

notifications:
  email:
    recipients:
    - rodrigobuas@gmail.com
    on_success: change
    on_failure: always

jobs:
  include:
    - name: lint
      stage: quality
      script: npm run lint

    - name: unit tests
      stage: test
      script: npm run unit-test

    - name: integration tests
      stage: test
      script: npm run int-test

